//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1873
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Example.Hello
{
    using System;
    using System.Collections.Generic;
    using Emc.Documentum.FS.Runtime;
    using Emc.Documentum.FS.Runtime.Context;
    
    
    /// <exclude/>
    public partial class HelloWorldServicePortClient : IHelloWorldService
    {
        
        /// <exclude/>
        public IServiceContext GetServiceContext()
        {
            throw new NotImplementedException();
        }
    }
    
    /// <summary>
    ///
    ///</summary>
    public interface IHelloWorldService : IContextHolder
    {
        
        /// <summary>
        ///
        ///</summary>
        string SayHello(string name);
    }
    
    /// <exclude/>
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.example.service.com/", ConfigurationName="HelloWorldServicePort")]
    public interface HelloWorldServicePort
    {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        /// <exclude/>
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(rt.fs.documentum.emc.com.ServiceException), Action="", Name="ServiceException", Namespace="http://rt.fs.documentum.emc.com/")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        sayHelloResponse sayHello(sayHelloRequest request);
    }
    
    /// <exclude/>
    [System.ServiceModel.MessageContractAttribute(WrapperName="sayHello", WrapperNamespace="http://ws.example.service.com/", IsWrapped=true)]
    public partial class sayHelloRequest
    {
        
        /// <exclude/>
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.example.service.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string name;
        
        /// <exclude/>
        public sayHelloRequest()
        {
        }
        
        /// <exclude/>
        public sayHelloRequest(string name)
        {
            this.name = name;
        }
    }
    
    /// <exclude/>
    [System.ServiceModel.MessageContractAttribute(WrapperName="sayHelloResponse", WrapperNamespace="http://ws.example.service.com/", IsWrapped=true)]
    public partial class sayHelloResponse
    {
        
        /// <exclude/>
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.example.service.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        /// <exclude/>
        public sayHelloResponse()
        {
        }
        
        /// <exclude/>
        public sayHelloResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    /// <exclude/>
    public interface HelloWorldServicePortChannel : HelloWorldServicePort, System.ServiceModel.IClientChannel
    {
    }
    
    /// <exclude/>
    public partial class HelloWorldServicePortClient : System.ServiceModel.ClientBase<HelloWorldServicePort>, HelloWorldServicePort
    {
        
        /// <exclude/>
        public HelloWorldServicePortClient()
        {
        }
        
        /// <exclude/>
        public HelloWorldServicePortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        /// <exclude/>
        public HelloWorldServicePortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        /// <exclude/>
        public HelloWorldServicePortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        /// <exclude/>
        public HelloWorldServicePortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        /// <exclude/>
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        sayHelloResponse HelloWorldServicePort.sayHello(sayHelloRequest request)
        {
            return base.Channel.sayHello(request);
        }
        
        /// <exclude/>
        [System.CLSCompliantAttribute(false)]
        public string sayHello(string name)
        {
            sayHelloRequest inValue = new sayHelloRequest();
            inValue.name = name;
            sayHelloResponse retVal = ((HelloWorldServicePort)(this)).sayHello(inValue);
            return retVal.@return;
        }
        
        /// <exclude/>
        public string SayHello(string name)
        {
            sayHelloRequest inValue = new sayHelloRequest();
            inValue.name = name;
            sayHelloResponse retVal = ((HelloWorldServicePort)(this)).sayHello(inValue);
            return retVal.@return;
        }
    }
}
namespace rt.fs.documentum.emc.com
{
    using System.Xml.Serialization;
    using System.Runtime.Serialization;
    
    
    /// <exclude/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Xml.Serialization.XmlSchemaProviderAttribute("ExportSchema")]
    [System.Xml.Serialization.XmlRootAttribute(IsNullable=false)]
    public partial class ServiceException : object, System.Xml.Serialization.IXmlSerializable
    {
        
        /// <exclude/>
        private System.Xml.XmlNode[] nodesField;
        
        /// <exclude/>
        private static System.Xml.XmlQualifiedName typeName = new System.Xml.XmlQualifiedName("ServiceException", "http://rt.fs.documentum.emc.com/");
        
        /// <exclude/>
        public System.Xml.XmlNode[] Nodes
        {
            get
            {
                return this.nodesField;
            }
            set
            {
                this.nodesField = value;
            }
        }
        
        /// <exclude/>
        public void ReadXml(System.Xml.XmlReader reader)
        {
            this.nodesField = System.Runtime.Serialization.XmlSerializableServices.ReadNodes(reader);
        }
        
        /// <exclude/>
        public void WriteXml(System.Xml.XmlWriter writer)
        {
            System.Runtime.Serialization.XmlSerializableServices.WriteNodes(writer, this.Nodes);
        }
        
        /// <exclude/>
        public System.Xml.Schema.XmlSchema GetSchema()
        {
            return null;
        }
        
        /// <exclude/>
        public static System.Xml.XmlQualifiedName ExportSchema(System.Xml.Schema.XmlSchemaSet schemas)
        {
            System.Runtime.Serialization.XmlSerializableServices.AddDefaultSchema(schemas, typeName);
            return typeName;
        }
    }
}

